// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniConnect.Infrastructure.Context;

#nullable disable

namespace UniConnect.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124221610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UniConnect.Domain.Entity.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PastaEstudoId")
                        .HasColumnType("int");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastaEstudoId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("arquivo", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Discussao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DiscussaoPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscussaoPaiId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("discussao", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.DiscussaoReacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscussaoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscussaoId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("discussao_reacao", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Visualizada")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioDestinoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mensagem", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.PastaEstudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PastaEstudoPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Visibilidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastaEstudoPaiId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pasta_estudo", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscussaoId")
                        .HasColumnType("int");

                    b.Property<int?>("RespostaPaiId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscussaoId");

                    b.HasIndex("RespostaPaiId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resposta", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.RespostaReacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RespostaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RespostaId");

                    b.HasIndex("UsuarioAlteracaoId");

                    b.HasIndex("UsuarioCriacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resposta_reacao", (string)null);
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FotoPerfilUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAlteracaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 11, 24, 19, 16, 10, 308, DateTimeKind.Local).AddTicks(458),
                            Email = "admin",
                            FotoPerfilUrl = "",
                            Nome = "Admin",
                            Senha = "UPHOAqVE0er6hexBH82HaEWie+OWSko2VBy2lzqVUHg=",
                            Telefone = "0000000",
                            TipoUsuario = 2,
                            UsuarioAlteracaoId = 1,
                            UsuarioCriacaoId = 0
                        });
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Arquivo", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.PastaEstudo", "PastaEstudo")
                        .WithMany("Arquivos")
                        .HasForeignKey("PastaEstudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("ArquivosCriados")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("PastaEstudo");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Discussao", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.Discussao", "DiscussaoPai")
                        .WithMany("SubDiscussoes")
                        .HasForeignKey("DiscussaoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("DiscussoesCriadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("DiscussaoPai");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.DiscussaoReacao", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.Discussao", "Discussao")
                        .WithMany("Reacoes")
                        .HasForeignKey("DiscussaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("ReacoesDiscussao")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Discussao");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Mensagem", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioDestino")
                        .WithMany("MensagensRecebidas")
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("MensagensEnviadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.PastaEstudo", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.PastaEstudo", "PastaPai")
                        .WithMany("SubPastas")
                        .HasForeignKey("PastaEstudoPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("PastasCriadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("PastaPai");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Resposta", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.Discussao", "Discussao")
                        .WithMany("Respostas")
                        .HasForeignKey("DiscussaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Resposta", "RespostaPai")
                        .WithMany("SubRespostas")
                        .HasForeignKey("RespostaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("RespostasCriadas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Discussao");

                    b.Navigation("RespostaPai");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.RespostaReacao", b =>
                {
                    b.HasOne("UniConnect.Domain.Entity.Resposta", "Resposta")
                        .WithMany("Reacoes")
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioAlteracao")
                        .WithMany()
                        .HasForeignKey("UsuarioAlteracaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UniConnect.Domain.Entity.Usuario", "UsuarioCriacao")
                        .WithMany()
                        .HasForeignKey("UsuarioCriacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UniConnect.Domain.Entity.Usuario", null)
                        .WithMany("ReacoesResposta")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Resposta");

                    b.Navigation("UsuarioAlteracao");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Discussao", b =>
                {
                    b.Navigation("Reacoes");

                    b.Navigation("Respostas");

                    b.Navigation("SubDiscussoes");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.PastaEstudo", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("SubPastas");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Resposta", b =>
                {
                    b.Navigation("Reacoes");

                    b.Navigation("SubRespostas");
                });

            modelBuilder.Entity("UniConnect.Domain.Entity.Usuario", b =>
                {
                    b.Navigation("ArquivosCriados");

                    b.Navigation("DiscussoesCriadas");

                    b.Navigation("MensagensEnviadas");

                    b.Navigation("MensagensRecebidas");

                    b.Navigation("PastasCriadas");

                    b.Navigation("ReacoesDiscussao");

                    b.Navigation("ReacoesResposta");

                    b.Navigation("RespostasCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
